export const SAGA_INIT_HOME_RECOMMEND = "SAGA_INIT_HOME_RECOMMEND";
export const INIT_HOME_RECOMMEND = "INIT_HOME_RECOMMEND";

export const SAGA_MORE_HOME_RECOMMEND = "SAGA_MORE_HOME_RECOMMEND";
export const MORE_HOME_RECOMMEND = "MORE_HOME_RECOMMEND";

export const SAGA_INIT_HOME_FOLLOW = "SAGA_INIT_HOME_FOLLOW";
export const INIT_HOME_FOLLOW = "INIT_HOME_FOLLOW";

export const SAGA_MORE_HOME_FOLLOW = "SAGA_MORE_HOME_FOLLOW";
export const MORE_HOME_FOLLOW = "MORE_HOME_FOLLOW";

export const SAGA_INIT_HOME_HOT = "SAGA_INIT_HOME_HOT";
export const INIT_HOME_HOT = "INIT_HOME_HOT";

export const SAGA_MORE_HOME_HOT = "SAGA_MORE_HOME_HOT";
export const MORE_HOME_HOT = "MORE_HOME_HOT";
