export const SAGA_INIT_HOME_RECOMMEND = "SAGA_INIT_HOME_RECOMMEND";
export const INIT_HOME_RECOMMEND = "INIT_HOME_RECOMMEND";

export const SAGA_MORE_HOME_RECOMMEND = "SAGA_MORE_HOME_RECOMMEND";
export const MORE_HOME_RECOMMEND = "MORE_HOME_RECOMMEND";

export const SAGA_INIT_HOME_FOLLOW = "SAGA_INIT_HOME_FOLLOW";
export const INIT_HOME_FOLLOW = "INIT_HOME_FOLLOW";

export const SAGA_MORE_HOME_FOLLOW = "SAGA_MORE_HOME_FOLLOW";
export const MORE_HOME_FOLLOW = "MORE_HOME_FOLLOW";

export const SAGA_INIT_HOME_HOT = "SAGA_INIT_HOME_HOT";
export const INIT_HOME_HOT = "INIT_HOME_HOT";

export const SAGA_MORE_HOME_HOT = "SAGA_MORE_HOME_HOT";
export const MORE_HOME_HOT = "MORE_HOME_HOT";

export const SAGA_INIT_PINS_RECOMMEND = "SAGA_INIT_PINS_RECOMMEND";
export const INIT_PINS_RECOMMEND = "INIT_PINS_RECOMMEND";

export const SAGA_MORE_PINS_RECOMMEND = "SAGA_MORE_PINS_RECOMMEND";
export const MORE_PINS_RECOMMEND = "MORE_PINS_RECOMMEND";

export const SAGA_INIT_PINS_HOT = "SAGA_INIT_PINS_HOT";
export const INIT_PINS_HOT = "INIT_PINS_HOT";

export const SAGA_MORE_PINS_HOT = "SAGA_MORE_PINS_HOT";
export const MORE_PINS_HOT = "MORE_PINS_HOT";

export const SAGA_INIT_PINS_FOLLOW = "SAGA_INIT_PINS_FOLLOW";
export const INIT_PINS_FOLLOW = "INIT_PINS_FOLLOW";

export const ADD_SEARCH_HISTORY = "ADD_SEARCH_HISTORY";

export const REMOVE_SEARCH_HISTORY = "REMOVE_SEARCH_HISTORY";

export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";

export const SAGA_INIT_BOOKS_ALL = "SAGA_INIT_BOOKS_ALL";
export const INIT_BOOKS_ALL = "INIT_BOOKS_ALL";

export const SAGA_MORE_BOOKS_ALL = "SAGA_MORE_BOOKS_ALL";
export const MORE_BOOKS_ALL = "MORE_BOOKS_ALL";

export const CHANGE_ARTICLE_THUMB_STATE = "CHANGE_ARTICLE_THUMB_STATE";

export const ADD_ARTICLE_WATCH_HISTORY = "ADD_ARTICLE_WATCH_HISTORY";

export const CHANGE_TAG_FOLLOWING_STATE = "CHANGE_TAG_FOLLOWING_STATE";

export const CHANGE_USER_FOLLOWING_STATE = "CHANGE_USER_FOLLOWING_STATE";

export const CHANGE_PIN_THUMB_STATE = "CHANGE_PIN_THUMB_STATE";
