export const SAGA_INIT_HOME_RECOMMEND = "SAGA_INIT_HOME_RECOMMEND";
export const INIT_HOME_RECOMMEND = "INIT_HOME_RECOMMEND";

export const SAGA_MORE_HOME_RECOMMEND = "SAGA_MORE_HOME_RECOMMEND";
export const MORE_HOME_RECOMMEND = "MORE_HOME_RECOMMEND";
